### ISSUE TITLE
Handle of non-ssl to ssl page.

### ISSUE THREAD

**Issue by nexobus** [Creare/magento-htaccess#11]
I have switched my store from http to https://

I have added these lines in the htaccess to account for visitors coming from an http page to the site so that they can get redirected to the https: version of the same page.

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%[REQUEST_URI}

However, all http:// requests are being redirected to the home page...

help?

How can the original htacess be modified to handle ssl...

Steve

**Comment by pweightman** [comment]
The problem is in your brackets it should be:

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

**Comment by nexobus** [comment]
that was a typo on my part it is a {  

Steve

**Comment by pweightman** [comment]
Personally I use the following syntax for this

RewriteEngine On 
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://www.yourdomain.com/$1 [R,L]

**Comment by nexobus** [comment]
I know it should be placed between the Mod_rewrite.c block but does putting it in the beginning or end matter?

**Comment by pweightman** [comment]
It should be the first entry in your mod_rewrite block, as all other rewrites should be done after you have converted to https

**Comment by nexobus** [comment]
great thank you..   I was able to get it working the way it should ...  thanks for the help patrick.
