### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by captainarmchair** [Creare/magento-htaccess#4]
Hi 

I am seeing error 500 when I test this .htaccess file. I saw someone had the same error 500 before so I tested to remove zlib compression out but no luck. All domain changes seems to correct. I cannot see any message in the log files either. 

What can I do to solve this? Iam using debian fully patched wheezy. 

Thanks

**Comment by geckos-geek** [comment]
@gputignano solution stopped the 505 error but am now getting a php error

**Comment by IcyApril** [comment]
Hi;

Just doing a little housekeeping. If this is a current issue, please create a new issue.

Thanks
